[workspace]
members = ["applet", "app"]
resolver = "2"

[workspace.dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["tokio", "wayland", "wgpu", "applet", "desktop"]

[workspace.dependencies]
log = "0.4.22"
pretty_env_logger = "0.5.0"
